'use strict';
const $=id=>document.getElementById(id);let data,run='sol',mode='views',index=0,timer=null;
const titles={overall_massing:'Overall massing',main_layout:'MAIN floor layout',second_layout:'SECOND floor layout',vertical_datums:'Vertical proportions',floor_slabs_voids:'Floor slabs & voids',door_openings:'Door openings',window_openings:'Window openings',roof_form:'Roof form',porch_stairs:'Porch & stairs',editable_valid_model:'Editable, valid geometry'};
const notes={views:'Verifier-rendered comparison: private reference on the left, saved candidate on the right. Cameras, lighting and scale match; horizontal translation is normalized. These are final-state renders, not screenshots from the agent’s session.',frames:'Screenshots captured during the agent’s UI session. Orange rings mark the recorded click coordinate on the resulting screenshot; page changes can move the original target. Use the action panel for exact inputs. Arrow keys move between frames.',drawings:'These seven 2D sheets were available to both agents. The construction workspace started empty; no DWG or 3D reference was supplied.'};
function items(){if(!data)return [];return run==='astra'&&mode!=='drawings'?[]:data[mode]}
function stop(){clearInterval(timer);timer=null;$('play').textContent='Play slideshow'}
function changeModel(value){stop();run=value;index=0;render()}
function changeMode(value){stop();mode=value;index=0;render()}
function render(){
 const sol=run==='sol',list=items(),has=list.length>0;index=Math.max(0,Math.min(index,list.length-1));
 document.querySelectorAll('[data-run]').forEach(b=>{b.classList.toggle('active',b.dataset.run===run);b.setAttribute('aria-pressed',String(b.dataset.run===run))});
 document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode))});
 $('modelTitle').textContent=sol?'GPT-5.6 Sol · high':'GPT-6 Astra · medium';$('score').textContent=data[run].score.toFixed(4);$('runStatus').textContent=sol?'Completed normally':'Interrupted · partial artifact';$('runId').textContent=data[run].id;
 $('modelSummary').textContent=sol?`A ${data.sol.elements}-element shell with roughly correct floor elevations. It omits doors, windows, interior partitions, porch and stairs.`:'The agent was interrupted by a model-capacity error after approximately 59 minutes. Its unfinished artifact received a 50.15% rubric score; this is not a completed-run comparison.';
 $('sourceLabel').textContent={views:'VERIFIER-RENDERED VIEWS',frames:'CAPTURED UI SCREENSHOTS',drawings:'AGENT INPUT · 2D ONLY'}[mode];$('viewNote').textContent=notes[mode];$('prompt').textContent=data.prompt;
 $('downloadModel').hidden=!sol;$('actionDetail').hidden=!has||mode!=='frames';$('stageImage').hidden=!has;$('emptyState').hidden=has;$('playback').hidden=!has;$('fullImage').hidden=!has;$('clickMarker').style.display='none';
 if(has){const item=list[index];$('stageImage').src=item.src;$('stageImage').alt=mode==='frames'?`Sol trajectory step ${item.step}: ${item.action}`:mode==='views'?`${item.label}: reference on left, Sol reconstruction on right`:`Input drawing ${item.label}`;$('fullImage').href=item.src;$('scrubber').max=list.length-1;$('scrubber').value=index;$('scrubber').setAttribute('aria-valuetext',`${index+1} of ${list.length}`);$('prev').disabled=index===0;$('next').disabled=index===list.length-1;
 $('imageCaption').textContent=mode==='frames'?`Frame ${index+1} / ${list.length} · Step ${item.step} · ${item.action}`:`${item.label} · ${index+1} / ${list.length}${mode==='views'?' · Reference ← → Sol':''}`;
 if(mode==='frames'){$('actionName').textContent=item.action;$('actionText').textContent=JSON.stringify(item.args,null,2)}
 }else{$('imageCaption').textContent='Astra · visual artifacts unavailable in archive'}
 renderCriteria();history.replaceState(null,'',`#${new URLSearchParams({run,mode,frame:index+1})}`)
}
function marker(){const item=items()[index],img=$('stageImage');if(mode!=='frames'||!item||item.action!=='click'||!Number.isFinite(item.args.x)||!Number.isFinite(item.args.y))return;const parent=$('imageStage').getBoundingClientRect(),r=img.getBoundingClientRect(),scale=Math.min(r.width/img.naturalWidth,r.height/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;const m=$('clickMarker');m.style.left=`${r.left-parent.left+(r.width-w)/2+item.args.x/item.size[0]*w}px`;m.style.top=`${r.top-parent.top+(r.height-h)/2+item.args.y/item.size[1]*h}px`;m.style.display='block'}
function renderCriteria(){const box=$('criteria');box.replaceChildren();$('rubricMeta').textContent=run==='sol'?'SOL · 10 CRITERIA':'ASTRA · BREAKDOWN NOT ARCHIVED';if(run!=='sol'){const p=document.createElement('p');p.style.padding='20px';p.textContent='Only the aggregate score and interruption status were retained for Astra. No per-criterion scores are inferred.';box.append(p);return}for(const c of data.criteria){const row=document.createElement('div');row.className='criterion';const name=document.createElement('div'),strong=document.createElement('strong'),weight=document.createElement('small');strong.textContent=titles[c.name]||c.name;weight.textContent=`${(c.weight*100).toFixed(0)}% weight`;name.append(strong,weight);const score=document.createElement('div');score.className='criterion-score';score.textContent=`${Math.round(c.value*100)} / 100`;const bar=document.createElement('div');bar.className='bar';const fill=document.createElement('span');fill.style.width=`${c.value*100}%`;bar.append(fill);score.append(bar);const reason=document.createElement('p');reason.textContent=c.reasoning;row.append(name,score,reason);box.append(row)}}
document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>changeModel(b.dataset.run));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>changeMode(b.dataset.mode));$('showSol').onclick=()=>changeModel('sol');$('prev').onclick=()=>{stop();index--;render()};$('next').onclick=()=>{stop();index++;render()};$('scrubber').oninput=event=>{stop();index=Number(event.target.value);render()};$('play').onclick=()=>{if(timer){stop();return}if(index===items().length-1)index=0;timer=setInterval(()=>{if(index>=items().length-1){stop();return}index++;render()},Number($('speed').value));$('play').textContent='Pause slideshow';render()};$('speed').onchange=()=>{if(timer){stop();$('play').click()}};$('present').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.viewer').requestFullscreen()}catch{$('imageCaption').textContent='Fullscreen is unavailable in this browser. Use Full resolution.'}};$('stageImage').onload=marker;window.addEventListener('resize',marker);document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)||!data)return;if(e.key==='ArrowRight'&&!$('next').disabled)$('next').click();if(e.key==='ArrowLeft'&&!$('prev').disabled)$('prev').click()});
fetch('data.json').then(r=>{if(!r.ok)throw Error('Evidence could not be loaded');return r.json()}).then(d=>{data=d;const p=new URLSearchParams(location.hash.slice(1));if(['sol','astra'].includes(p.get('run')))run=p.get('run');if(['views','frames','drawings'].includes(p.get('mode')))mode=p.get('mode');index=Math.max(0,(Number(p.get('frame'))||1)-1);render()}).catch(e=>{$('stageImage').hidden=true;$('imageCaption').textContent=e.message});
